### PR TITLE
Upgrade pickadate to v3.5.6, extract style overrides to its own partial and allow months navigation in datepicker

### PR DESCRIPTION
**Pull request by dcarral**

### CODE REVIEW

**Comment by moonglum** [comment]
Woha, 2000 lines added. Is that external code? A little hard to review :smile:

**Comment by dcarral** [comment]
Indeed, it upgrades [pickadate.js](http://amsul.ca/pickadate.js/)  (from v3.1.4 to v3.5.6). 

The changelog can be found here: https://github.com/amsul/pickadate.js/blob/master/CHANGELOG.md ;)

By the way, I've updated the PR with a mini-commit which fixes https://github.com/eurucamp/eurucamp-activities/issues/166 (it comes handy to have already extracted the pickadate's overrides in this branch)

**Comment by dcarral** [comment]
Nice to know that PR's names editions are streamed here. I'm sorry for the mess ;)

**Comment by dcarral** [comment]
Re-pinging @moonglum after a while. What could we do in order to move this forward?

**Comment by moonglum** [comment]
Yep, looking good :+1:

**Pull request merged**
