### PR TITLE
Run staging Shelly cloud in staging env

### PR DESCRIPTION
**Pull request by maser**

### CODE REVIEW

**Comment by moonglum** [comment]
Is there a staging environment in Rails? I thought there are only three (`PRODUCTION`, `TESTING` and `DEVELOPMENT`)?

**Comment by maser** [comment]
There is `config/environments/staging.rb` and the staging environment gets mentioned in `config/application.yml`.

You can define your own environment. There are some people who say you should always run in `production` and configure via environment variables, but as we already configure via YAML...

**Comment by moonglum** [comment]
*scratches head* But shouldn't staging be as close to production as possible?

**Comment by maser** [comment]
Yes. The only difference is the domain name:

```yaml
staging:
  <<: *defaults
  host: "activities-staging.eurucamp.org"
```

If we move this into a HOST environment variable, we can configure everything via `.env.production` and run staging in production env. That would be nice, but also more work than this change.

I don’t like that we use dotenv for some things and `application.yml` for others…

**Comment by maser** [comment]
Waaaaiiit a minute, that staging domain name is not even correct, needs a fix, too!

**Comment by moonglum** [comment]
Ok, so do you want to put the fixed domain name in here, too?

**Comment by maser** [comment]
Yes, I just did.

**Comment by moonglum** [comment]
Awesome!

**Pull request merged**
